# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Fetch omnia_config.yml inputs
  ansible.builtin.include_tasks: input_vars.yml
  run_once: true

- name: Prereq vars
  ansible.builtin.include_tasks: _prereq.yml

- name: Fresh cluster - Include common tasks
  ansible.builtin.include_tasks: common.yml

- name: Ensure local directories for slurm ctl save ops
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_user_group }}"
    mode: "{{ common_mode }}"
  loop:
    - "{{ slurm_conf_dict['StateSaveLocation'] }}"

- name: Check if slurm.conf exists
  ansible.builtin.stat:
    path: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/slurm.conf"
  register: p

- name: Create slurm.conf for ctld only
  ansible.builtin.template:
    src: "slurm.conf.j2"
    dest: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/slurm.conf"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "{{ conf_file_mode }}"
  when: not p.stat.exists
  run_once: true
  notify:
    - Restart slurmctld

- name: Create cgroup.conf for ctld only
  ansible.builtin.template:
    src: "cgroup.conf.j2"
    dest: "{{ item }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "{{ conf_file_mode }}"
  loop:
    - "{{ slurm_share_prefix }}{{ slurm_config_dir }}/cgroup.conf"
  notify:
    - Restart slurmctld

- name: Add this slurm controller in conf
  ansible.builtin.lineinfile:
    path: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/slurm.conf"
    line: "SlurmctldHost={{ inventory_hostname_short }}"
    insertafter: '^ClusterName=*'

# TODO: To read packages from the software config json based on role name ex: slurm_control_node
- name: Install slurm ctld packages
  ansible.builtin.command:
    argv: "{{ dnf_command + slurm_controller_packages[ansible_os_family] }}"
  register: dnf_out
  failed_when: dnf_out.rc != 0
  changed_when: dnf_out.rc == 0
  timeout: 300
  ignore_errors: true

- name: Create files
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    owner: "{{ slurm_user }}"
    group: "{{ slurm_user_group }}"
    mode: "{{ slurm_mode }}"
  loop:
    - "{{ slurm_conf_dict['SlurmctldLogFile'] }}"
    - "{{ slurm_conf_dict['SlurmctldPidFile'] }}"

#  if service installed locally - this following copy not required
- name: Copy the slurctld service local for nfs
  ansible.builtin.copy:
    src: "{{ installroot }}{{ slurmctld_service_default_path }}"
    dest: "{{ slurmctld_service_default_path }}"
    remote_src: true
    mode: preserve
  when: (slurm_installation_type == nfs_share_slurm) and _force_install_nfs

- name: Enable the service
  ansible.builtin.systemd_service:
    daemon_reload: true

# Edit service
- name: Enable the service
  ansible.builtin.service:
    name: slurmctld
    enabled: true
  register: ctld_service
  no_log: true

- name: Ctld service path
  ansible.builtin.set_fact:
    ctld_service_path: "{{ ctld_service['status']['FragmentPath'] | default(slurmctld_service_default_path) }}"

- name: Edit the service
  community.general.ini_file:
    path: "{{ ctld_service_path }}"
    section: Unit
    option: ConditionPathExists
    state: absent
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "{{ conf_file_mode }}"
  notify:
    - Reload slurmctld
    - Restart slurmctld

- name: Edit the service to fetch specific conf
  community.general.ini_file:
    path: "{{ ctld_service_path }}"
    section: Service
    option: ExecStart
    value: "{{ installroot }}usr/sbin/slurmctld -D -f {{ slurm_share_prefix }}{{ slurm_config_dir }}/slurm.conf -s $SLURMCTLD_OPTIONS"
    no_extra_spaces: true
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "{{ conf_file_mode }}"
  notify:
    - Reload slurmctld
    - Restart slurmctld

- name: Set ctld specific env file
  community.general.ini_file:
    path: "/etc/sysconfig/slurmctld"
    option: "LD_LIBRARY_PATH"
    state: "{{ 'present' if (slurm_installation_type == nfs_share_slurm) else 'absent' }}"
    value: "{{ installroot }}usr/lib64"
    no_extra_spaces: true
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "{{ conf_file_mode }}"
  notify:
    - Reload slurmctld
    - Restart slurmctld

- name: Add the controller to list
  ansible.builtin.set_fact:
    ctld_list: "{{ (ctld_list + [inventory_hostname_short]) | unique | list }}"
  run_once: true

- name: Set the common env vars
  ansible.builtin.include_tasks: _env_set.yml
